### ISSUE TITLE
Docker: log to stdout by default

### ISSUE THREAD

**Issue by kilrau** [rsksmart/rskj#2155]
Quite some hassle to get standard stuff like `docker logs -f` & co working otherwise OR at least share a sample `docker-compose.yml` here in the repo and on dockerhub with this entrypoint to avoid newbies lose time getting logs to work:
```
  rsk:
    image: rsksmart/rskj:latest
    logging: *default-logging
    user: root
    entrypoint: "java -Dlogging.stdout=INFO -Dlogging=OFF -Dkeyvalue.datasource=rocksdb -Drpc.providers.web.http.bind_address=0.0.0.0 -Drpc.providers.web.http.hosts.0=localhost -Drpc.providers.web.http.hosts.1=127.0.0.1 -Drpc.providers.web.http.hosts.2=::1 -cp rsk.jar co.rsk.Start"
    volumes:
      - /media/disk/rsk:/root/.rsk
 ```
